### ISSUE TITLE
Problem installing development version 

### ISSUE THREAD

**Issue by mkhoshle** [MDAnalysis/mdanalysis#1841]
Hi, 
I have a forked repository of mdanalysis. I am trying to install the development version of it by (pip install --editable . ) but I am getting the following error:
I have cython installed in my virtual environment but I do not know why I am getting this error. Have you seen this before?

### Expected behaviour
pip install --editable . 

### Actual behaviour
Complete output from command python setup.py egg_info:
   Cython version 0.28.1 was found but won't be used: version 0.16 or greater is required because it offers a handy parallelization module
   Attempting to autodetect OpenMP support... Compiler supports OpenMP
   Will attempt to use Cython.
   Couldn't find a Cython installation. Not recompiling cython extensions.
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/nfs/homes4/mkhoshle/Library/mdanalysis/package/setup.py", line 482, in <module>
       exts, cythonfiles = extensions(config)
     File "/nfs/homes4/mkhoshle/Library/mdanalysis/package/setup.py", line 386, in extensions
       "failed/disabled Cython build.".format(source))
   IOError: Source file 'MDAnalysis/lib/formats/libdcd.c' not found. This might be caused by a missing Cython install, or a failed/disabled Cython build.
  
   ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /nfs/homes4/mkhoshle/Library/mdanalysis/package/ 

### Code to reproduce the behaviour

``` python
pip install --editable . 
```

### Currently version of MDAnalysis:
0.17.0

**Comment by kain88-de** [comment]
please update your fork. This was a temporary band-aid to fix cython compilation errors the disallowed cython 0.28. The latest version of develop works with the newest cython compiler

**Comment by kain88-de** [comment]
Sorry, #1833  will fix this. Until then please use cython 0.27

**Comment by kain88-de** [comment]
should be fixed now

**Comment by orbeckst** [comment]
@mkhoshle has this problem been fixed?

**Comment by mkhoshle** [comment]
@kain88-de @orbeckst  No, unfortunately, it is not fixed. If I downgrade my cython it works. But with the latest version it fails.
