### ISSUE TITLE
XDR offsets are not deleted after the tests

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#669]
The tests that use XTC or TR files produce cached offsets for these trajectories (files names .*_offset.npz). These files remain in the `testsuite/MDAnalysisTests/data` directory and never get clened. In addition to being messy, it makes some tests fail after a git checkout (probably because it messes with the ctimes).

Here is an example of error:

```
======================================================================
ERROR: test_persistent_offsets_size_mismatch (MDAnalysisTests.coordinates.test_xdr.TestXTCReader_offsets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jon/dev/mdanalysis/testsuite/MDAnalysisTests/coordinates/test_xdr.py", line 765, in test_persistent_offsets_size_mismatch
    assert_equal(warn[0].message.args,
IndexError: list index out of range

----------------------------------------------------------------------
```

ping @kain88-de

**Comment by kain88-de** [comment]
ah that isn't due to the cached offsets still being there. There tests actually run in a tempdir.

What happens here is that the warning isn't caught. This is fixed in #656

**Comment by jbarnoud** [comment]
@kain88-de #656 seems to have fix the traceback I git. But the offset files are still not deleted after the tests. The fact that the tests run in a temporary directory has nothing to do with that since the offset files are store beside the trajectory and not in the work directory.

Steps to reproduce:

```bash
$ find  -name '*_offsets.npz' -delete  # make sure there is no offset files
# run the tests
$ find ./ -name '*_offsets.npz'
./testsuite/MDAnalysisTests/data/.adk_oplsaa.trr_offsets.npz
./testsuite/MDAnalysisTests/data/.gram_A_identical_frames.xtc_offsets.npz
./testsuite/MDAnalysisTests/data/.cobrotoxin.trr_offsets.npz
./testsuite/MDAnalysisTests/data/.cobrotoxin.xtc_offsets.npz
./testsuite/MDAnalysisTests/data/coordinates/.test.trr_offsets.npz
./testsuite/MDAnalysisTests/data/coordinates/.test.xtc_offsets.npz
./testsuite/MDAnalysisTests/data/.adk_oplsaa.xtc_offsets.npz
```

**Comment by kain88-de** [comment]
They were already stored for the old offsets files. This is a problem that hard to solve. I don't know exactly what tests are creating them but I assume it is for the once that are not run in a temporary directory where we just test the reading and check if the coordinates are ok.

To solve this we would either have to delete them manually after every test (eg call `os.unlink`/`shutil.remove`) or we have to copy the trajectories to a temporary directory.

I have added them to the `.gitignore` as well like the old files. So they shouldn't bother anyone during normal development.

**Comment by jbarnoud** [comment]
I have them ignored too, and they are hidden file. This is why I do not 
think about them most of the time and I just lost some time. Indeed, I 
pulled the changes you made on how the offset is validated, and it 
conflicted with my previous offset (the number of atoms was not saved, 
so it could not be read leading to a KeyError). It took me some time to 
realize it was because I still had the old offsets.

Is it possible to have some cleanup done at the end of the test run? 
Because, then we could delete all the offset files when nose is done.

In the mean time, I will add the cleanup in my own test script.

**Comment by kain88-de** [comment]
> Is it possible to have some cleanup done at the end of the test run? Because, then we could delete all the offset files when nose is done.

Well we could add a clean up part to `./mda_nosetests` that's actually not a bad idea.

**Comment by orbeckst** [comment]
Having the offset files created besides the test trajectories is really dirty and it might even interfere with running tests in parallel, especially the ones testing offset creation and validity.

How about running *every* trajectory test in tempdir and use *hard links* if possible and copy if no hard links are available? Some simple accessor function such as `stage_file()` that one can put in a `setUp()` along the lines of 
```python
def setUp(self):
      self.workdir = tmpdir.TempDir().name
      self.trajectory = stage_file(filenames.XTC)
      self.universe = Universe(filenames.GRO, self.trajectory)
```

**Comment by mnmelo** [comment]
Alternatively, we could disable offset saving for all general coordinate tests (we have a flag to allow that, don't we?).
Offset-specific tests are already run in their own tempdir, right?

**Comment by orbeckst** [comment]
On 12 Feb, 2016, at 18:46, mnmelo wrote:

> Alternatively, we could disable offset saving for all general coordinate tests (we have a flag to allow that, don't we?).

I actually don't know if you can disable it.

In any case, I'd prefer to run most tests as they would be run in the wild, just to catch the odd interaction.

> Offset-specific tests are already run in their own tempdir, right?

Do these tests already include copying of trajectories to tmpdir??

**Comment by mnmelo** [comment]
Hmm, you're right, @orbeckst, I should've looked at the actual code. Trajectories aren't currently copied/linked into the tempdirs.

I like your solution. Do you think there's a way to run it as a decorator, for minimal test-code impact?
Like a modification to `@run_in_tempdir` where we can pass arguments to the decorator of files we want to stage?

**Comment by jbarnoud** [comment]
I am not sure we want to run all the tests without the cache offset. Most of the time, a XTC file is used only as reference coordinates; recalculating the offset every time would drastically increase the time needed to run the tests.

The cleanest solution would be not to calculate the offset at all when it is not needed (we do not care about the offset when we iterate over all frames) and to copy the trajectory in a temporary directory when we specifically test for the offset.

The easiest solution is to clean the mess at the end. It is true that we could have issue with concurrent writing of the offset. I never encountered the issue, though.

**Comment by kain88-de** [comment]
Yeah copying and regenerating the offsets every time will make the tests run a lot longer. I'm  also for just cleaning up afterwards.

**Comment by kain88-de** [comment]
So I've tried to just add the file deletions to `mda_nosetests`

```python
# clean up temporary files
folder = resource_filename('MDAnalysisTests', '/data/')
for offset_file in glob(folder + '.*.npz'):
    os.remove(offset_file)
```

But this doesn't work the code is not run anymore. I suspect the `run` method from nose that we call directly exists the script.

**Comment by jbarnoud** [comment]
I tried with a module level tearDown method but it breaks 
parallelization. The best solution, I think, would be to have a nose 
plugin taking care of that. According to @mnmelo, it should be doable.

**Comment by mnmelo** [comment]
@kain88-de: I already discussed this with @jbarnoud, but if you're going the plugin way, `finalize` is probably the hook you're looking for.
It shouldn't be hard to copy the structure of an existing plugin. If you want I can take care of it over the weekend.

**Comment by kain88-de** [comment]
That would be great. Can you try that the plugin is only run once after all tests have finished?

**Comment by mnmelo** [comment]
Yes, that's the point of `finalize`. I'll try it out and let you know.

**Comment by jbarnoud** [comment]
@mnmelo @kain88-de For the record, here is the function I used when I tried the `teardown_package` method:

```python
from pkg_resources import resource_filename

def teardown_package():
    """
    Final cleanups. This is executed after the last test.
    """
    # Delete the cached offsets
    for root, dirs, files in os.walk(resource_filename(__name__, 'data')):
        for file in files:
            if file.endswith('_offsets.npz'):
                os.unlink(os.path.join(root, file))
```

**Comment by mnmelo** [comment]
In the meantime @jbarnoud and I came to an interesting conclusion (rather obvious, if you think of it):
when installed system-wide, `MDAnalysisTests` will never be able to write offsets unless run as root.
We have no test checking for successful offset writes. Should we?

**Comment by jbarnoud** [comment]
What concerns me slightly more is that we do not have tests that make sure we can *read* the offset. Or did I miss it @kain88-de ?

**Comment by kain88-de** [comment]
I think we only check that we regenerate them in that case. I can't remember that we explicitly check that no warning is thrown. But that should be easy to test.
