### ISSUE TITLE
Should resids be independent of the Residue IDs defined in a Topology

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#793]
Resids should be 0-indexed and independent from the ids defined in the topology. Especially the one we print with `resids`.  I noticed that the `resids` we print are the same as the `ids` as defined in the topology. Topologies mostly use a 1-index behavior and we use a 0-index. This can lead to outputs that are not necessarily easily explained, especially using ranges. I currently have a student new to MD-simulations and this is confusing to him (and me until I figured out what happened).
### Expected behaviour

Resids behave the same on range indexing as numpy arrays
### Actual behaviour

The resid is shifted by one.
### Code to reproduce the behaviour

``` python
>>> import MDAnalysis as mda
>>> import numpy as np
>>> from MDAnalysisTests.datafiles import PSF

>>> u = mda.Universe(PSF)
>>> u.atoms.residues[15:20].resids
[16, 17, 18, 19, 20]

>>>  a = np.arange(20)
>>> a[15:20]
array([15, 16, 17, 18, 19])
```

Intuitively I would expect that both range commands print the same numbers.
### Currently version of MDAnalysis:

0.14.0

**Comment by richardjgowers** [comment]
Yeah @dotsdl and I have spoke about this to death.  What we've chosen to do in 363 is resid is just a name that the topology gives to residues (so 1 based, 100 based, or whatever), I guess like numbers in a sports team!  Then resindex is what you want, a 0 based pointer to the residue.  We're using resindex extensively for the residue property tables.

**Comment by kain88-de** [comment]
having `resid` and `resindex` is still confusing. But I get why you have chosen it. Anywhy that is better then the current solution.

**Comment by kain88-de** [comment]
OK so this is another bug that gets fixed with #363. Should we track those now with a separate label to know which issues should be closed once the branch is merged?

**Comment by dotsdl** [comment]
@kain88-de I think this is a good idea. I just made a "solved by 363" tag.

**Comment by dotsdl** [comment]
I'll go through all the issues and add this tag to each I find.

**Comment by richardjgowers** [comment]
@dotsdl surely it's easier to find the issues that we didn't fix right? \s

**Comment by richardjgowers** [comment]
Ok so resids are as defined in the topology file, there's also resindices which is what you could slice `u.residues` to get the same `ResidueGroup`.  ie `u.residues[rg.resindices]` returns `rg` again.
